name: Build and Test and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  push_docker_image:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up QEMU 
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub 
      uses: docker/login-action@v3 
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push 
      uses: docker/build-push-action@v5 
      with: 
        push: true 
        tags: whataten/test:${{ github.sha }}