name: Push To Docker Hub

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Commit Message as Image Tag
      id: get-commit-message
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        IMAGE_TAG=$(echo "$COMMIT_MESSAGE" | awk -F ':' '{print $2}' | tr -d '[:space:]')
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven    

    - name: Build with Maven
      run: mvn -B clean package --file backend/pom.xml

    - name: Login to Docker Hub 
      uses: docker/login-action@v3 
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU 
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v3

    - name: Build and push 
      uses: docker/build-push-action@v5 
      with: 
        push: true 
        tags: whataten/test:$IMAGE_TAG